title: JSON Resume
description: "JSON Resume is a community driven open source initiative to create a JSON based standard for resumes."
permalink: pretty
markdown: kramdown
include: [/.well-known]
plugins:
  - jekyll/web_monetization
payment_pointer:
  - $ilp.uphold.com/wR4wXD6jZqJz # Seth Falco
